"""empty message

Revision ID: 6641ed666118
Revises: 85099125f09b
Create Date: 2024-05-31 23:27:58.153756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6641ed666118'
down_revision = '85099125f09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recipe',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_title', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('recipe_ingredients', sa.String(), nullable=False),
    sa.Column('recipe_directions', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recipe')
    # ### end Alembic commands ###
